name: FACED
n_chans: 32
duration: 10

classifier:
  n_classes: 9
  pooling: "last"

data_loader:
  dataset:
    _target_: downstream_tasks.dataloaders.LMDBDataset
    path: ${data_root}/FACED/processed
    electrodes: ['FP1', 'FP2', 'FZ', 'F3', 'F4', 'F7', 'F8', 'FC1', 'FC2', 'FC5', 'FC6', 'CZ', 'C3', 'C4', 'T3', 'T4', 'CP1', 'CP2', 'CP5', 'CP6', 'PZ', 'P3', 'P4', 'T5', 'T6', 'PO3', 'PO4', 'OZ', 'O1', 'O2', 'A2', 'A1']
    scale_factor: 1000.0
  batch_size: 64
  seed: ${seed}
  splits: ["train", "val", "test"]

linear_probing:
  n_epochs: 20
  patience: 10
  warmup_epochs: 3
  mixup: False
  dropout: 0.05 
  optimizer:
    lr: 5e-3
  scheduler:
    patience: 6

fine_tuning:
  n_epochs: 200
  patience: 50
  warmup_epochs: 5
  mixup: False 
  dropout: 0.1
  optimizer:
    lr: 1e-4
  scheduler:
    patience: 6

clip: 100



